//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.reports = new HashSet<report>();
        }
    
        public long id { get; set; }
        public long clientid { get; set; }
        public long productid { get; set; }
        public Nullable<long> deliveryid { get; set; }
        public Nullable<decimal> productprice { get; set; }
        public Nullable<decimal> deliveryprice { get; set; }
        public string location { get; set; }
        public string paymentmode { get; set; }
        public decimal totalcost { get; set; }
        public long producttype { get; set; }
        public string productrespond { get; set; }
        public string deliveryrespond { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public System.DateTime modifieddate { get; set; }
    
        public virtual client client { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
    }
}
