//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientcomment
    {
        public long id { get; set; }
        public long clientid { get; set; }
        public Nullable<long> memberid { get; set; }
        public Nullable<long> deliveryid { get; set; }
        public Nullable<int> rate { get; set; }
        public string note { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual client client { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual product product { get; set; }
    }
}
