//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public delivery()
        {
            this.bookings = new HashSet<booking>();
            this.clientcomments = new HashSet<clientcomment>();
            this.deliverytypes = new HashSet<deliverytype>();
        }
    
        public long id { get; set; }
        public string deliverycode { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<decimal> lowestprice { get; set; }
        public Nullable<decimal> highestprice { get; set; }
        public Nullable<int> quality { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string disctrict { get; set; }
        public string city { get; set; }
        public long userid { get; set; }
        public Nullable<decimal> commission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientcomment> clientcomments { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliverytype> deliverytypes { get; set; }
    }
}
