//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public long id { get; set; }
        public string from { get; set; }
        public long to { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public System.DateTime datetime { get; set; }
        public bool status { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    
        public virtual user user { get; set; }
    }
}
