//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbwebEntities : DbContext
    {
        public dbwebEntities()
            : base("name=dbwebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<clientcomment> clientcomments { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<deliveryprice> deliveryprices { get; set; }
        public virtual DbSet<deliverytype> deliverytypes { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<moneytransaction> moneytransactions { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productprice> productprices { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<video> videos { get; set; }
    }
}
