//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneytransaction
    {
        public long id { get; set; }
        public string code { get; set; }
        public byte[] receiptphoto { get; set; }
        public decimal value { get; set; }
        public System.DateTime trandate { get; set; }
        public string remark { get; set; }
        public string status { get; set; }
        public long sourceid { get; set; }
        public long destinationid { get; set; }
        public Nullable<System.DateTime> paymentdate { get; set; }
        public string ccname { get; set; }
        public string ccno { get; set; }
        public Nullable<int> ccexpiredmonth { get; set; }
        public Nullable<int> ccexpiredyear { get; set; }
        public string ccpin { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
