//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class productprice
    {
        public long id { get; set; }
        public long producttypeid { get; set; }
        public decimal price { get; set; }
        public bool active { get; set; }
        public Nullable<long> productid { get; set; }
        public Nullable<decimal> reward { get; set; }
    
        public virtual producttype producttype { get; set; }
    }
}
