//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public long id { get; set; }
        public long bookingid { get; set; }
        public string content { get; set; }
        public string systemrespond { get; set; }
        public Nullable<decimal> refundamount { get; set; }
    
        public virtual booking booking { get; set; }
    }
}
