//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        public long id { get; set; }
        public long memberid { get; set; }
        public byte[] data { get; set; }
        public string videolink { get; set; }
        public System.DateTime uploadeddate { get; set; }
        public string videodescription { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<bool> isvisible { get; set; }
        public Nullable<bool> vipmemberonly { get; set; }
        public string status { get; set; }
    
        public virtual product product { get; set; }
    }
}
