//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class clientcomment : ModelBase
    {
        [DataMember]
        public long id { get; set; }
        [DataMember]
        public long clientid { get; set; }
        [DataMember]
        public Nullable<long> memberid { get; set; }
        [DataMember]
        public Nullable<long> deliveryid { get; set; }
        [DataMember]
        public Nullable<int> rate { get; set; }
        [DataMember]
        public string note { get; set; }
        [DataMember]
        public System.DateTime createddate { get; set; }
        [DataMember]
        public virtual client client { get; set; }
        [DataMember]
        public virtual delivery delivery { get; set; }
        [DataMember]
        public virtual product product { get; set; }
    }
}
