//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class client : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.bookings = new HashSet<booking>();
            this.clientcomments = new HashSet<clientcomment>();
        }
        [DataMember]
        public long id { get; set; }
        [DataMember]
        public string clientcode { get; set; }
        [DataMember]
        public int paymentmode { get; set; }
        [DataMember]
        public string ccholder { get; set; }
        [DataMember]
        public string ccnumber { get; set; }
        [DataMember]
        public Nullable<int> ccexpiredmonth { get; set; }
        [DataMember]
        public Nullable<int> ccexpiredyear { get; set; }
        [DataMember]
        public string ccpin { get; set; }
        [DataMember]
        public long userid { get; set; }
        [DataMember]
        public bool isvalid { get; set; }
        [DataMember]
        public System.DateTime createddate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> modifieddate { get; set; }
        [DataMember]
        public decimal balance { get; set; }
        [DataMember]
        public int cancelcount { get; set; }
        [DataMember]
        public virtual ICollection<booking> bookings { get; set; }
        [DataMember]
        public virtual user user { get; set; }
        [DataMember]
        public virtual ICollection<clientcomment> clientcomments { get; set; }
    }
}
