//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Client : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Bookings = new HashSet<Booking>();
            this.ClientComments = new HashSet<ClientComment>();
        }
       
        [DataMember]
        public string Code { get; set; }
        [DataMember]
        public int PaymentMode { get; set; }
        [DataMember]
        public string CCHolder { get; set; }
        [DataMember]
        public string CCNumber { get; set; }
        [DataMember]
        public Nullable<int> CCExpiredMonth { get; set; }
        [DataMember]
        public Nullable<int> CCExpiredYear { get; set; }
        [DataMember]
        public string CCPin { get; set; }
        [DataMember]
        public long UserId { get; set; }
        [DataMember]
        public bool IsValid { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public decimal Balance { get; set; }
        [DataMember]
        public int CancelCount { get; set; }
        [DataMember]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientComment> ClientComments { get; set; }
        [DataMember]
        public virtual User User { get; set; }
    }
}
