//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class deliverytype : ModelBase
    {
        [DataMember]
        public long id { get; set; }
        [DataMember]
        public long deliveryid { get; set; }
        [DataMember]
        public long deliverycode { get; set; }
        [DataMember]
        public string deliverydescription { get; set; }
        [DataMember]
        public bool active { get; set; }
        [DataMember]
        public string extrafee { get; set; }
        [DataMember]
        public System.DateTime createddate { get; set; }
        [DataMember]
        public System.DateTime modifieddate { get; set; }
    }
}
