//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class DeliveryType : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryType()
        {
            this.DeliveryPrices = new HashSet<DeliveryPrice>();
        }
       
        [DataMember]
        public long DeliveryId { get; set; }
        [DataMember]
        public long Code { get; set; }
        [DataMember]
        public string DeliveryDescription { get; set; }
        [DataMember]
        public bool Active { get; set; }
        [DataMember]
        public string ExtraFee { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }
        [DataMember]
        public Nullable<decimal> Price { get; set; }
        [DataMember]

        public virtual Delivery Delivery { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryPrice> DeliveryPrices { get; set; }
    }
}
