//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class delivery : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public delivery()
        {
            this.bookings = new HashSet<booking>();
            this.clientcomments = new HashSet<clientcomment>();
        }
        
        [DataMember]
        public string deliverycode { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public string address { get; set; }
        [DataMember]
        public Nullable<decimal> lowestprice { get; set; }
        [DataMember]
        public Nullable<decimal> highestprice { get; set; }
        [DataMember]
        public Nullable<int> quality { get; set; }
        [DataMember]
        public string phone { get; set; }
        [DataMember]
        public string email { get; set; }
        [DataMember]
        public string disctrict { get; set; }
        [DataMember]
        public string city { get; set; }
        [DataMember]
        public long userid { get; set; }
        [DataMember]
        public Nullable<decimal> commission { get; set; }
        [DataMember]
        public virtual ICollection<booking> bookings { get; set; }
        [DataMember]
        public virtual ICollection<clientcomment> clientcomments { get; set; }
        [DataMember]
        public virtual user user { get; set; }
    }
}
