//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class deliveryprice
    {
        [DataMember]
        public Nullable<long> deliverytypeid { get; set; }
        [DataMember]
        public Nullable<decimal> price { get; set; }
        [DataMember]
        public Nullable<bool> active { get; set; }
        [DataMember]
        public virtual deliverytype deliverytype { get; set; }
    }
}
