//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class MoneyTransaction:ModelBase
    {
        [DataMember]
        public long Id { get; set; }
        [DataMember]
        public string Code { get; set; }
        [DataMember]
        public byte[] ReceiptPhoto { get; set; }
        [DataMember]
        public decimal Value { get; set; }
        [DataMember]
        public System.DateTime Trandate { get; set; }
        [DataMember]
        public string Remark { get; set; }
        [DataMember]
        public string Status { get; set; }
        [DataMember]
        public long SourceId { get; set; }
        [DataMember]
        public long DestinationId { get; set; }
        [DataMember]
        public Nullable<System.DateTime> PaymentDate { get; set; }
        [DataMember]
        public string CCName { get; set; }
        [DataMember]
        public string CCNumber { get; set; }
        [DataMember]
        public Nullable<int> CCExpiredMonth { get; set; }
        [DataMember]
        public Nullable<int> CCExpiredYear { get; set; }
        [DataMember]
        public string CCPin { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public Nullable<long> TrackingId { get; set; }
        [DataMember]

        public virtual User User { get; set; }
        [DataMember]
        public virtual User User1 { get; set; }
        [DataMember]
        public virtual Tracking Tracking { get; set; }
    }
}
