//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class ProductPrice : ModelBase
    {
       
        [DataMember]
        public long ProductTypeId { get; set; }
        [DataMember]
        public decimal Price { get; set; }
        [DataMember]
        public bool Active { get; set; }
        [DataMember]
        public Nullable<long> ProductId { get; set; }
        [DataMember]
        public Nullable<decimal> Reward { get; set; }
        [DataMember]

        public virtual ProductType ProductType { get; set; }
        [DataMember]
        public virtual Product Product { get; set; }
    }
}
