//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class productprice : ModelBase
    {
     
        [DataMember]
        public long producttypeid { get; set; }
        [DataMember]
        public decimal price { get; set; }
        [DataMember]
        public bool active { get; set; }
        [DataMember]
        public Nullable<long> productid { get; set; }
        [DataMember]
        public Nullable<decimal> reward { get; set; }
        [DataMember]

        public virtual producttype producttype { get; set; }
    }
}
