//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class producttype : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producttype()
        {
            this.productprices = new HashSet<productprice>();
        }
        [DataMember]
        public long id { get; set; }
        [DataMember]
        public string producttype1 { get; set; }
        [DataMember]
        public bool actvice { get; set; }
        [DataMember]
        public string flag { get; set; }
        [DataMember]

        public virtual ICollection<productprice> productprices { get; set; }
    }
}
