//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class product : ModelBase
    {
        public product()
        {
            this.bookings = new HashSet<booking>();
            this.clientcomments = new HashSet<clientcomment>();
            this.videos = new HashSet<video>();
        }
        [DataMember]
        public long id { get; set; }
        [DataMember]
        public string productcode { get; set; }
        [DataMember]
        public string group { get; set; }
        [DataMember]
        public string language1 { get; set; }
        [DataMember]
        public string language2 { get; set; }
        [DataMember]
        public decimal price { get; set; }
        [DataMember]
        public string preferrablelocation { get; set; }
        [DataMember]
        public string bankname { get; set; }
        [DataMember]
        public string bankaccount { get; set; }
        [DataMember]
        public string bankaccnumber { get; set; }
        [DataMember]
        public System.DateTime createddate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> modifeddate { get; set; }
        [DataMember]
        public bool isactive { get; set; }
        [DataMember]
        public bool isblocked { get; set; }
        [DataMember]
        public Nullable<bool> isavailable { get; set; }
        [DataMember]
        public int cancelcount { get; set; }
        [DataMember]
        public long userid { get; set; }
        [DataMember]
        public string productdescription { get; set; }
        [DataMember]
        public decimal balance { get; set; }
        [DataMember]
        public Nullable<decimal> commission { get; set; }
        [DataMember]
        public Nullable<decimal> reward { get; set; }       

        [DataMember]
        public virtual ICollection<booking> bookings { get; set; }
        [DataMember]
        public virtual ICollection<clientcomment> clientcomments { get; set; }
        public virtual user user { get; set; }
        [DataMember]
        public virtual ICollection<video> videos { get; set; }
    }
}
