//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Product : ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bookings = new HashSet<Booking>();
            this.ClientComments = new HashSet<ClientComment>();
            this.ProductPrices = new HashSet<ProductPrice>();
            this.Videos = new HashSet<Video>();
        }
       
        [DataMember]
        public string Code { get; set; }
        [DataMember]
        public string Group { get; set; }
        [DataMember]
        public string Language1 { get; set; }
        [DataMember]
        public string Language2 { get; set; }
        [DataMember]
        public decimal Price { get; set; }
        [DataMember]
        public string PreferrableLocation { get; set; }
        [DataMember]
        public string BankName { get; set; }
        [DataMember]
        public string BankAccount { get; set; }
        [DataMember]
        public string BankAccNumber { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifedDate { get; set; }
        [DataMember]
        public bool IsActive { get; set; }
        [DataMember]
        public bool IsBlocked { get; set; }
        [DataMember]
        public Nullable<bool> IsAvailable { get; set; }
        [DataMember]
        public int CancelCount { get; set; }
        [DataMember]
        public long UserId { get; set; }
        [DataMember]
        public string ProductDescription { get; set; }
        [DataMember]
        public decimal Balance { get; set; }
        [DataMember]
        public Nullable<decimal> Commission { get; set; }
        [DataMember]
        public Nullable<decimal> Reward { get; set; }
        [DataMember]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientComment> ClientComments { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrice> ProductPrices { get; set; }
        [DataMember]
        public virtual User User { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
    }
}
