//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Tracking:ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tracking()
        {
            this.MoneyTransactions = new HashSet<MoneyTransaction>();
            this.Bookings = new HashSet<Booking>();
        }
  
        [DataMember]
        public long BookingId { get; set; }
        [DataMember]
        public string ProductConfirm { get; set; }
        [DataMember]
        public string ClientConfirm { get; set; }
        [DataMember]
        public string DeliveryConfirm { get; set; }
        [DataMember]
        public System.DateTime DateTime { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }
        [DataMember]
        public string RemarkProduct { get; set; }
        [DataMember]
        public string RemarkClient { get; set; }
        [DataMember]
        public string RemarkDelivery { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyTransaction> MoneyTransactions { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [DataMember]
        public virtual Booking Booking { get; set; }
    }
}
