//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class user:ModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.clients = new HashSet<client>();
            this.deliveries = new HashSet<delivery>();
            this.messages = new HashSet<message>();
            this.moneytransactions = new HashSet<moneytransaction>();
            this.moneytransactions1 = new HashSet<moneytransaction>();
            this.photos = new HashSet<photo>();
            this.products = new HashSet<product>();
        }        
        [DataMember]
        public string username { get; set; }
        [DataMember]
        public string password { get; set; }
        [DataMember]
        public string fullname { get; set; }
        [DataMember]
        public System.DateTime dateofbirth { get; set; }
        [DataMember]
        public bool active { get; set; }
        [DataMember]
        public string email { get; set; }
        [DataMember]
        public string phone { get; set; }
        [DataMember]
        public string accounttype { get; set; }
        [DataMember]
        public bool isblocked { get; set; }
        [DataMember]
        public string gcmkey { get; set; }
        [DataMember]
        public Nullable<bool> isnotify { get; set; }
        [DataMember]
        public short securityquestionid { get; set; }
        [DataMember]
        public string securityanswer { get; set; }
        [DataMember]
        public Nullable<System.DateTime> createddate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> modifieddate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> lastlogin { get; set; }

        [DataMember]
        public virtual ICollection<client> clients { get; set; }
        [DataMember]
        public virtual ICollection<delivery> deliveries { get; set; }
        [DataMember]
        public virtual ICollection<message> messages { get; set; }
        [DataMember]
        public virtual ICollection<moneytransaction> moneytransactions { get; set; }
        [DataMember]
        public virtual ICollection<moneytransaction> moneytransactions1 { get; set; }
        [DataMember]
        public virtual ICollection<photo> photos { get; set; }
        [DataMember]
        public virtual ICollection<product> products { get; set; }
    }
}
