//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference =true)]
    public partial class Video : ModelBase
    {
       
        [DataMember]
        public long ProductId { get; set; }
        [DataMember]
        public byte[] Source { get; set; }
        [DataMember]
        public string VideoLink { get; set; }
        [DataMember]
        public System.DateTime UploadedDate { get; set; }
        [DataMember]
        public string VideoDescription { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public Nullable<bool> IsVisible { get; set; }
        [DataMember]
        public Nullable<bool> VIPMemberOnly { get; set; }
        [DataMember]
        public string Status { get; set; }
        [DataMember]

        public virtual Product Product { get; set; }
    }
}
