//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using Models.Common;
    using System.Runtime.Serialization;

    public partial class video : ModelBase
    {
       
        [DataMember]
        public long memberid { get; set; }
        [DataMember]
        public byte[] data { get; set; }
        [DataMember]
        public string videolink { get; set; }
        [DataMember]
        public System.DateTime uploadeddate { get; set; }
        [DataMember]
        public string videodescription { get; set; }
        [DataMember]
        public Nullable<System.DateTime> createddate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> modifieddate { get; set; }
        [DataMember]
        public Nullable<bool> isvisible { get; set; }
        [DataMember]
        public Nullable<bool> vipmemberonly { get; set; }
        [DataMember]
        public string status { get; set; }
        [DataMember]

        public virtual product product { get; set; }
    }
}
